server:
  port: ${server_port:9090}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}

zuul:
  prefix: /api
#  Uncomment to disable services automatically registering in Zuul
#  ignoredServices: '*'

  routes:
    account:
      path: /account/**
      serviceId: account-service

spring:
  application:
    name: zuul-server

management:
  security:
    enabled: false
